---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oep-status
  namespace: __app_namespace__
  labels:
    app: oep-status
    tier: backend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: oep-status
      tier: backend
  template:
    metadata:
      labels:
        app: oep-status
        tier: backend
    spec:
      volumes:
        - name: application-properties
          configMap:
            name: oep-application
        - name: zipstorage
          azureFile:
            secretName: azure-storage-secret
            shareName: farepository
            readOnly: true
        - name: wwwroot
          emptyDir: {}
      initContainers:
        - name: copy
          image: docker.io/library/busybox:1.28
          command:
            - /bin/sh
            - -c
          args:
            - cp /tmp/open-esl-status-__app_version__.jar /home/app.jar
          resources: {}
          volumeMounts:
            - name: zipstorage
              mountPath: /tmp
            - name: wwwroot
              mountPath: /home
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - image: azul/zulu-openjdk-alpine:20-latest
          name: oep-status
          command:
            - sh
            - -c
          args:
            - >
              cd /application

              java -jar app.jar --spring.profiles.active=prod -Dspring.config.location=/application/config/application-prod.properties
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /application/config
              name: application-properties
            - mountPath: /application
              name: wwwroot
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              memory: 1200Mi
            requests:
              cpu: 800m
              memory: 1000Mi
          readinessProbe:
            httpGet:
              path: /api/v1/ping
              port: 8080
              scheme: HTTP
            timeoutSeconds: 240
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/v1/ping
              port: 8080
              scheme: HTTP
            timeoutSeconds: 240
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: JVM_OPTIONS
              value: -XX:MaxRAMPercentage=80.0 -XX:+UseG1GC -XX:+UseContainerSupport
                -XX:-OmitStackTraceInFastThrow
                -Djava.security.egd=file:/dev/./urandom
            - name: BUS_CS_FRONT
              valueFrom:
                secretKeyRef:
                  name: oep-connectivity
                  key: bus.cs.frontal
                  optional: false
            - name: BUS_CS_BACKEND
              valueFrom:
                secretKeyRef:
                  name: oep-connectivity
                  key: bus.cs.backend
                  optional: false
            - name: BUS_CS_SEARCH_PRIMARY
              valueFrom:
                secretKeyRef:
                  name: oep-connectivity
                  key: bus.cs.search.primary
                  optional: false
            - name: BUS_CS_SEARCH_SECONDARY
              valueFrom:
                secretKeyRef:
                  name: oep-connectivity
                  key: bus.cs.search.secondary
                  optional: false
            - name: STORAGE_CS
              valueFrom:
                secretKeyRef:
                  name: oep-connectivity
                  key: tasks.storage.cs
                  optional: false
            - name: API_KEY1
              valueFrom:
                secretKeyRef:
                  name: oep-application
                  key: api.key1
                  optional: true
            - name: API_KEY2
              valueFrom:
                secretKeyRef:
                  name: oep-application
                  key: api.key2
                  optional: true
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: oep-application
                  key: db.user
                  optional: false
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: oep-application
                  key: db.password
                  optional: false
            - name: DB_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: oep-connectivity
                  key: db.host.namespace
                  optional: false
            - name: REDIS_HOST_READ
              valueFrom:
                secretKeyRef:
                  name: oep-connectivity
                  key: redis.host.read
                  optional: false
            - name: REDIS_HOST_WRITE
              valueFrom:
                secretKeyRef:
                  name: oep-connectivity
                  key: redis.host.write
                  optional: false
            - name: REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: oep-application
                  key: redis.user
                  optional: false
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oep-application
                  key: redis.password
                  optional: false
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: oep-sa
      serviceAccount: oep-sa
      securityContext: {}
      schedulerName: default-scheduler

---
apiVersion: v1
kind: Service
metadata:
  name: oep-status
  namespace: __app_namespace__
  labels:
    expose: 'true'
spec:
  selector:
    app: oep-status
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ope-status-hpa
  namespace: __app_namespace__
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oep-status
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
